name: Newsfragments

on:
  pull_request_target:
    branches-ignore:
      - 'dials-?.*'

jobs:
  rename-news:
    name: Newsfragment
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - name: Added a newsfragment
        run: |
          set -x
          echo "Triggering commit: ${GITHUB_REF} ${GITHUB_SHA}"
          git fetch --unshallow
          git log HEAD -n 1
          treediff="$(git diff-tree  HEAD ${{ github.event.pull_request.base.sha }} -- newsfragments/)"
          if [[ -z "${treediff}" ]]; then
            echo "::error ::PR Branch is missing a newsfragment. Please add one with a number or named XXX.<type>."
            exit 1
          else
            echo "✅  Newsfragment entry present"
          fi
      - name: Rename placeholder newsfragments
        env:
          SSH_AUTH_SOCK: /tmp/ssh_agent.sock
        run: |
          set -x
          if ls newsfragments/XXX.* 1> /dev/null 2>&1; then
            # Setup SSH access
            mkdir -p ~/.ssh
            ssh-keyscan github.com >> ~/.ssh/known_hosts
            ssh-agent -a ${SSH_AUTH_SOCK} > /dev/null
            ssh-add - <<< "${{ secrets.SSH_PRIVATE_KEY }}"
            # Now setup git
            git config user.name "github-actions[bot]"
            git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
            HEAD_REPO="${{github.event.pull_request.head.repo.full_name}}"
            HEAD_BRANCH="${{ github.event.pull_request.head.ref }}"
            message=""
            git remote add fork git@github.com:$HEAD_REPO.git
            echo "Check the connection"
            ssh -v git@github.com || true
            echo "done"
            #https://x-access-token:${GITHUB_TOKEN}@github.com/$HEAD_REPO.git
            for fragment in newsfragments/XXX.*; do
              target_file="$(echo "${fragment}" | sed "s/XXX/${{github.event.number}}/")"
              git mv $fragment $target_file
              git add $target_file
              if [[ -z "${message}" ]]; then
                message="Rename ${fragment} to ${target_file}"
              else
                message="Rename XXX.* to ${{github.event.number}}.*"
              fi
            done
            git commit -m "${message}"
            git push fork HEAD:"${HEAD_BRANCH}"
          else
            echo "No Newsfragments need to be renamed."
          fi
